### ISSUE TITLE
Separate toolchain details from build system

### ISSUE THREAD

**Issue by johnmcfarlane** [cpp-best-practices/cpp_starter_project#123]
If you really want to go the extra mile in providing a good example of how modern CMake should be used, it's arguably a good idea to avoid mentioning the details of tools and tool chains (e.g. specific analysers, package managers, compiler flags etc.) from within the CMakeLists.txt files. Those files should be reserved for describing how the source fits together to make binary artefacts.

The root CMakeLists.txt in particular is doing double duty as a script for enabling many, varied workflows. They could mostly/all be removed from CMake, or isolated into .cmake files which aren't invoked from CMakeLists.txt but are instead invoked using `cmake` in script mode. The ideal is achieving a clean separation between the build system and the other tools on display in this project.

Examples:
* All of the compiler options could be passing in via the `cmake` configuration command ([e.g. using the language flags variables](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html)) or collected into toolchain files ([example](https://github.com/johnmcfarlane/cnl/blob/main/.github/workflows/test.yml#L262), [more explanation](https://stackoverflow.com/a/63527508/671509)). This makes it easier to add or extend tool chain support.
* The build system could be made package manager-agnostic by removing all reference to Conan. A clean separation is generally encourage by the Conan team, and it's straightforward to achieve using generators such as [cmake_find_package](https://docs.conan.io/en/1.34/integrations/build_system/cmake/cmake_find_package_generator.html?highlight=cmake_find_package).
* Tools like Clang-Tidy can be enabled from outside the CMakeLists.txt files for cleaner separation.

In general, if a variable starts with `CMAKE_`, then it's ideally passed into the build system, rather than set from inside of it.

**Comment by aminya** [comment]
I am pretty sure that this was fixed in #169

**Comment by johnmcfarlane** [comment]
@aminya I am less sure. But I don't recommend you reopen this issue as it's highly unlikely to be addressed.

One of the aims of a good build system is to keep things simple and self-contained. That this build system is large enough to have spilled into a separate repo means it has gone in the opposite direction. Let's take a look at the original three examples...

> * All of the compiler options could be passing in via the cmake configuration command (e.g. using the language flags variables) or collected into toolchain files (example, more explanation). This makes it easier to add or extend tool chain support.

This is still not the case. Toolchain-specific matters (such as compiler options) are now so deeply buried in the build system, they're pulled out into a repo of their own! This can only make it harder to add or extend toolchain support.

> * The build system could be made package manager-agnostic by removing all reference to Conan. A clean separation is generally encourage by the Conan team, and it's straightforward to achieve using generators such as cmake_find_package.

Over the past year, the Conan team have taken great strides in separating Conan-specific concerns from CMake code, making it easier than ever - primarily through use of toolchain files - to switch between competing package managers from *outside* the _/CMakeLists.txt_ call-graph. Again, #169 takes things in quite the opposite direction, expanding Conan-specific logic to fill an entire script. A streamlined build system should work seamlessly with any package manager through the open–closed principle. But this project would appear to be hard to *extend* to novel package managers, while requiring *modification* to work with those novel systems.

> * Tools like Clang-Tidy can be enabled from outside the CMakeLists.txt files for cleaner separation.

If a new static analyser received CMake support tomorrow, would it be as easy to use in this project as Clang-Tidy? In a simple project, the full facility of clang-tidy is enabled by, e.g. passing `-DCMAKE_CXX_CLANG_TIDY=clang` into the configuration stage and providing a .clang-tidy file with a few vital settings such as `WarningsAsErrors: '*'`. Perhaps the 20-odd lines of script in _StaticAnalyzers.cmake_ (plus the layers of abstraction that gets `cmake` to them) does something I'm missing, but is this the way we want to show off CMake to beginners?

And generally, if there's a problem and Clang-Tidy - or any of the other tools here - is missing. Do we want the project to just silently succeed? Do we want any of the errors that Clang-Tidy would have caught to go unfixed? When you unpeel all the layers of `if/else` statements like [this one](https://github.com/cpp-best-practices/project_options/blob/0d3e8a2f7d3484491f81afb8bd85cc4f08703f38/src/StaticAnalyzers.cmake#L24), what you see is a system that is trying to be helpful by adding accidental complexity. It is defending against errors that its user really ought to find out about and fix. In doing so, it is smothering the fire with coal.

Those are just three examples of good principles to follow when setting up a build system. I could continue. But in short, if someone was curious about CMake and wanted good example of how to use it, I would only steer them further away from this project as a result of #169.

**Comment by aminya** [comment]
In my opinion, the things you describe are **non-goals** for a starter project. We don't want to make the build highly flexible (totally the opposite of best practices) or invent our build system to accommodate the existing fragmented C++ build scripts. 

We want to provide a project that sets the **good defaults** that the compilers, CMake, Vcpkg, Conan, etc all **overlooked** and did not provide.

Take a look at the Cargo ecosystem and the 80,000 packages that are built with it. None of them require any external flags or scripts. It is just `cargo build`. Similarly for many of the other modern package managers.

**Comment by johnmcfarlane** [comment]
For anyone who is curious to learn more, here's [the WSS project](https://github.com/johnmcfarlane/wss/) which serves as an example of how to maintain a C++ project with simple build and package management systems.

**Comment by aminya** [comment]
Because you brought it up, I want to clarify why your project doesn't meet the criteria of cpp-best-practices:

- Your toolchains [only support Linux](https://github.com/johnmcfarlane/wss/tree/main/.github/workflows/toolchains), which ignores most of the developers on other platforms like Windows
- The shell scripts are all Bash, which is not supported on Windows.
- No cross-platform sanitizer support
- Your CI only tests Ubuntu.
- The build scripts are not reusable and it encourages copy-pasting. It requires hand-crafting calls to different tools like Conan, clang-tidy, etc.
- 13000 lines of shell script however don't look simple to me. 

![image](https://user-images.githubusercontent.com/16418197/155389164-27b261cb-708f-4544-a6de-dc1309abd213.png)

**Comment by AntonioCS** [comment]
<off-topic> @aminya What tool did you use to generate that useful table? </off-topic>

**Comment by aminya** [comment]
@AntonioCS It is called `scc`! 🙂
https://github.com/boyter/scc

**Comment by AntonioCS** [comment]
@aminya Thank you and apologies for the off-topic

**Comment by johnmcfarlane** [comment]
I think you misunderstand me. I'm not trying to meet the criteria of the cpp-best-practices GitHub group. But thanks for the feedback. I'll incorporate the valid points into the project when I get some spare time.
